from .json_modifier import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

# 告诉 ComfyUI 这里的 JS 文件需要被加载
WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
